cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<uuid:product_id>/',views.full_remove, name='full_remove'),
]

musicproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('search/', include('search_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('musicshop.urls')),
    path('cart/',include('cart.urls')),
    path('order/', include('order.urls')),
    path('vouchers/' ,include('vouchers.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musicshop/urls.py
from django.urls import path

from . import views

app_name= 'musicshop'
urlpatterns =[
 
    path('',views.prod_list, name='all_products'),
    path('<uuid:category_id>/', views.prod_list, name='products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>/' ,views.product_detail, name= 'product_detail'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
 path('thanks/<int:order_id>/', views.thanks, name='thanks'),
 path('history/', views.orderHistory.as_view(), name='order_history'),
 path('<int:order_id>/',views.orderDetail.as_view(), name='order_detail'),
] 

search_app/urls.py
from django.urls import path
from .views import SearchResultListView

app_name = 'search_app'

urlpatterns = [
    path('', SearchResultListView.as_view(), name='searchResult'),
]

templates/base.html
{% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
        rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
        crossorigin="anonymous"
/>
        <title>{% block title %} music shop {% endblock title %}</title>
    </head>
   
  
    <body>
        <div class="container">
            <div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
                {% include 'top-navbar.html' %}
            </div>
    
            {% include 'header.html' %}
            {% include 'navbar.html' %}
            {% block content %}
            {% endblock content %}
            {% include 'footer.html'%}
        </div>
        <!-- JavaScript Bundle with Popper -->
        <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    </body>
    </html>

templates/footer.html
<div class = "footer navbar-fixed-bottom my-footer">
    <p class = "text-center">&copy; Online Music Shop. All Rights Reserved.</p>
</div>

templates/header.html
{% load static %}

<header>
    <div style="text-align: center;">
        <a href="{% url 'musicshop:all_products' %}">
        <img src="{% static 'images/logo.png' %}" 
        alt="Gino's Shop"></a>
    </div>
</header>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" ariacontrols="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                 
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" ariaexpanded="false">
                Shop
                </a>
               
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'musicshop:all_products' %}">All Products</a></li>
                        {% for cat in links %}
                            <li><a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
                        {% endfor %}
                </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Your Cart</a>
                </li>
                {% if item_count > 0 %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i
                    class="fas fa-shopping-cart">({{item_count}})</i></a>
                </li>
                {% endif %}
               
            </ul>
            <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

templates/top-navbar.html
<div class="container">
    <div class="my_custom_menu">
        <ul>
            {% if user.is_authenticated %}
            <li>
                Welcome, <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown" 
                aria-haspopup="true" aria-expanded="false">{{ user.username }} 
                <i class="fas fa-user-circle"></i></a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="{% url 'order:order_history' %}" class="dropdown-item">Order History</a>
                </div>

            </li>

            <li>
                <a href="{% url 'logout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
            </li>
            <li>
                <a href="{% url 'login' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
            </li>
            {% endif %}
        </ul>
        
    </div>
</div>